// iSpan centralized strings

const strings = {
  en: {
    appName: 'iSpan',
    tagline: 'Inspiring stronger minds & bodies',
    subtitle: 'India\'s first integrated wellness platform for schools',
    loginTitle: 'Welcome to iSpan',
    loginSub: 'A complete educative wellness ecosystem — emotional health, physiotherapy, nutrition, and strength conditioning for students, teachers, and parents.',
    role: 'Role',
    email: 'Email',
    password: 'Password',
    signIn: 'Sign in',
    signOut: 'Sign out',
    student: 'Student',
    admin: 'Admin',
    parent: 'Parent',
    teacher: 'Teacher',
    studentDashboard: 'My Wellness',
    adminDashboard: 'Dashboard',
    parentDashboard: 'Child Progress',
    videos: 'Wellness programs',
    progress: 'Progress',
    markComplete: 'Mark Complete',
    completed: 'Completed',
    enrolled: 'Students enrolled',
    completion: 'Completion %',
    watchedVideos: 'Programs completed',
    demoCreds: 'Demo access',
    schoolId: 'School ID',
    startToday: 'Get started',
    trustworthy: 'Built for schools that believe in holistic development.',
    whatChildLearns: 'What your child is learning',
    resources: 'Parent resources',
    quickNotes: 'Milestones and wellness notes',
    switchView: 'View as',
    dashboard: 'Dashboard',
    students: 'Students',
    reports: 'Reports',
    curriculum: 'Programs',
    settings: 'Settings',
    myLearning: 'My Programs',
    achievements: 'Achievements',
    pricing: 'Pricing',
    mostPopular: 'Most Popular',
    getStarted: 'Get started',
    enterprise: 'Enterprise wellness for schools',
    studentProgress: 'Student progress',
    classOverview: 'Class-wise overview',
    filterByClass: 'Filter by class',
    allClasses: 'All classes',
    thisWeek: 'this week',
    privacySafe: 'Privacy-safe visibility',
    aggregateOnly: 'Aggregate only',
    modulesVisible: 'Programs visible',
    upToDate: 'Up to date',
    milestones: 'Milestones and wellness notes',
    thisMonth: 'This month',
    pillarPsychology: 'Emotional Health',
    pillarPhysio: 'Physiotherapy',
    pillarNutrition: 'Nutrition',
    pillarStrength: 'Strength & Conditioning',
    forStudents: 'For Students',
    forTeachers: 'For Teachers',
    forParents: 'For Parents',
    studentsDesc: 'Emotional & psychological support, IQ & EQ development, nutrition guidance, and physiotherapy.',
    teachersDesc: 'Identifying concerns in students, work-life balance, mental health support, and fitness programs.',
    parentsDesc: 'Child psychology, screen time management, nutrition and fitness routines for growing children.',
    ourPillars: 'Our 4 pillars',
    pillarSubtitle: 'True wellness is a science-backed approach that combines emotional health, physiotherapy, nutrition, and strength conditioning.',
    holistic: 'Complete educative wellness ecosystem',
    holisticDesc: 'iSpan creates a balanced ecosystem of learning, emotional growth and overall well being for students, teachers and parents.',
    inspiring: 'Inspiring stronger minds and bodies',
    inspiringDesc: 'The iSpan app is a revolutionary child development & wellness platform designed for schools — from kindergarten to Grade 10.',
  },
  hi: {
    appName: 'आईस्पैन',
    tagline: 'मजबूत मन और शरीर को प्रेरित करना',
    subtitle: 'स्कूलों के लिए भारत का पहला एकीकृत वेलनेस प्लेटफॉर्म',
    loginTitle: 'iSpan में आपका स्वागत है',
    loginSub: 'छात्रों, शिक्षकों और अभिभावकों के लिए मनोविज्ञान, फिजियोथेरेपी, पोषण और शक्ति प्रशिक्षण।',
    role: 'भूमिका',
    email: 'ईमेल',
    password: 'पासवर्ड',
    signIn: 'साइन इन',
    signOut: 'साइन आउट',
    student: 'छात्र',
    admin: 'प्रशासक',
    parent: 'अभिभावक',
    teacher: 'शिक्षक',
    studentDashboard: 'मेरा वेलनेस',
    adminDashboard: 'डैशबोर्ड',
    parentDashboard: 'बच्चे की प्रगति',
    videos: 'वेलनेस कार्यक्रम',
    progress: 'प्रगति',
    markComplete: 'पूर्ण करें',
    completed: 'पूर्ण',
    enrolled: 'नामांकित छात्र',
    completion: 'पूर्णता %',
    watchedVideos: 'पूर्ण कार्यक्रम',
    demoCreds: 'डेमो एक्सेस',
    schoolId: 'स्कूल ID',
    startToday: 'शुरू करें',
    trustworthy: 'समग्र विकास में विश्वास रखने वाले स्कूलों के लिए बनाया गया।',
    whatChildLearns: 'आपका बच्चा क्या सीख रहा है',
    resources: 'अभिभावक संसाधन',
    quickNotes: 'माइलस्टोन और वेलनेस नोट्स',
    switchView: 'देखें',
    dashboard: 'डैशबोर्ड',
    students: 'छात्र',
    reports: 'रिपोर्ट',
    curriculum: 'कार्यक्रम',
    settings: 'सेटिंग्स',
    myLearning: 'मेरे कार्यक्रम',
    achievements: 'उपलब्धियाँ',
    pricing: 'प्राइसिंग',
    mostPopular: 'सबसे लोकप्रिय',
    getStarted: 'शुरू करें',
    enterprise: 'स्कूलों के लिए enterprise वेलनेस',
    studentProgress: 'छात्र प्रगति',
    classOverview: 'कक्षा-वार अवलोकन',
    filterByClass: 'कक्षा से फ़िल्टर करें',
    allClasses: 'सभी कक्षाएँ',
    thisWeek: 'इस हफ्ते',
    privacySafe: 'गोपनीयता-सुरक्षित दृश्यता',
    aggregateOnly: 'केवल एग्रीगेट',
    modulesVisible: 'कार्यक्रम दिख रहे हैं',
    upToDate: 'अप टू डेट',
    milestones: 'माइलस्टोन और वेलनेस नोट्स',
    thisMonth: 'इस महीने',
    pillarPsychology: 'भावनात्मक स्वास्थ्य',
    pillarPhysio: 'फिजियोथेरेपी',
    pillarNutrition: 'पोषण',
    pillarStrength: 'शक्ति और सुदृढ़ीकरण',
    forStudents: 'छात्रों के लिए',
    forTeachers: 'शिक्षकों के लिए',
    forParents: 'अभिभावकों के लिए',
    studentsDesc: 'भावनात्मक और मनोवैज्ञानिक सहायता, IQ और EQ विकास, पोषण मार्गदर्शन।',
    teachersDesc: 'छात्रों में चिंताओं की पहचान, कार्य-जीवन संतुलन, मानसिक स्वास्थ्य सहायता।',
    parentsDesc: 'बच्चे का मनोविज्ञान, स्क्रीन टाइम प्रबंधन, पोषण और फिटनेस दिनचर्या।',
    ourPillars: 'हमारे 4 स्तंभ',
    pillarSubtitle: 'सच्चा वेलनेस एक वैज्ञानिक दृष्टिकोण है जो मनोविज्ञान, फिजियोथेरेपी, पोषण और शक्ति प्रशिक्षण को जोड़ता है।',
    holistic: 'संपूर्ण शैक्षिक वेलनेस इकोसिस्टम',
    holisticDesc: 'iSpan छात्रों, शिक्षकों और अभिभावकों के लिए सीखने, भावनात्मक विकास और समग्र कल्याण का एक संतुलित इकोसिस्टम बनाता है।',
    inspiring: 'मजबूत मन और शरीर को प्रेरित करना',
    inspiringDesc: 'iSpan ऐप एक क्रांतिकारी बच्चे के विकास और वेलनेस प्लेटफॉर्म है जो स्कूलों के लिए डिज़ाइन किया गया है।',
  },
};

export function t(lang, key) {
  return strings[lang]?.[key] ?? strings.en[key] ?? key;
}

export default strings;
