// Centralized strings — one place to swap or add languages later.
// Usage: import { t } from '@/lib/strings'; t(lang, 'adminDashboard');

const strings = {
  en: {
    appName: 'MindWell',
    tagline: 'A school wellbeing platform that feels warm for families and credible for schools.',
    loginTitle: 'Welcome to MindWell',
    loginSub: 'Support wellbeing across classrooms, homes, and school leadership with a clean, enterprise-ready experience.',
    role: 'Role',
    email: 'Email',
    password: 'Password',
    signIn: 'Sign in',
    signOut: 'Sign out',
    student: 'Student',
    admin: 'Admin',
    parent: 'Parent',
    studentDashboard: 'My Learning',
    adminDashboard: 'Dashboard',
    parentDashboard: 'Child Progress',
    videos: 'Wellbeing videos',
    progress: 'Progress',
    markComplete: 'Mark Complete',
    completed: 'Completed',
    enrolled: 'Students enrolled',
    completion: 'Completion %',
    watchedVideos: 'Videos watched',
    demoCreds: 'Demo access',
    schoolId: 'School ID',
    startToday: 'Get started',
    trustworthy: 'Built for multi-school rollouts, role-based access, and clean reporting.',
    whatChildLearns: 'What your child is learning',
    resources: 'Parent resources',
    quickNotes: 'Milestones and wellbeing notes',
    switchView: 'View as',
    dashboard: 'Dashboard',
    students: 'Students',
    reports: 'Reports',
    curriculum: 'Curriculum',
    settings: 'Settings',
    myLearning: 'My Learning',
    achievements: 'Achievements',
    pricing: 'Pricing',
    mostPopular: 'Most Popular',
    getStarted: 'Get started',
    enterprise: 'Enterprise-ready for schools at scale',
    studentProgress: 'Student progress',
    classOverview: 'Class-wise overview',
    filterByClass: 'Filter by class',
    allClasses: 'All classes',
    thisWeek: 'this week',
    privacySafe: 'Privacy-safe visibility',
    aggregateOnly: 'Aggregate only',
    modulesVisible: 'Modules visible',
    upToDate: 'Up to date',
    milestones: 'Milestones and wellbeing notes',
    thisMonth: 'This month',
  },
  hi: {
    appName: 'माइंडवेल',
    tagline: 'परिवारों के लिए गर्मजोशी, स्कूलों के लिए भरोसेमंद wellbeing platform.',
    loginTitle: 'माइंडवेल में आपका स्वागत है',
    loginSub: 'क्लासरूम, घर और स्कूल leadership — तीनों के लिए एक polished experience.',
    role: 'भूमिका',
    email: 'ईमेल',
    password: 'पासवर्ड',
    signIn: 'साइन इन',
    signOut: 'साइन आउट',
    student: 'छात्र',
    admin: 'प्रशासक',
    parent: 'अभिभावक',
    studentDashboard: 'मेरी पढ़ाई',
    adminDashboard: 'डैशबोर्ड',
    parentDashboard: 'बच्चे की प्रगति',
    videos: 'वेलबीइंग वीडियो',
    progress: 'प्रगति',
    markComplete: 'पूर्ण करें',
    completed: 'पूर्ण',
    enrolled: 'नामांकित छात्र',
    completion: 'पूर्णता %',
    watchedVideos: 'देखे गए वीडियो',
    demoCreds: 'डेमो एक्सेस',
    schoolId: 'स्कूल ID',
    startToday: 'शुरू करें',
    trustworthy: 'Multi-school rollout, role-based access, और clean reporting के लिए बनाया गया.',
    whatChildLearns: 'आपका बच्चा क्या सीख रहा है',
    resources: 'अभिभावक संसाधन',
    quickNotes: 'माइलस्टोन और wellbeing notes',
    switchView: 'देखें',
    dashboard: 'डैशबोर्ड',
    students: 'छात्र',
    reports: 'रिपोर्ट',
    curriculum: 'पाठ्यक्रम',
    settings: 'सेटिंग्स',
    myLearning: 'मेरी पढ़ाई',
    achievements: 'उपलब्धियाँ',
    pricing: 'प्राइसिंग',
    mostPopular: 'सबसे लोकप्रिय',
    getStarted: 'शुरू करें',
    enterprise: 'बड़े स्कूलों के लिए enterprise-ready',
    studentProgress: 'छात्र प्रगति',
    classOverview: 'कक्षा-वार अवलोकन',
    filterByClass: 'कक्षा से फ़िल्टर करें',
    allClasses: 'सभी कक्षाएँ',
    thisWeek: 'इस हफ्ते',
    privacySafe: 'गोपनीयता-सुरक्षित दृश्यता',
    aggregateOnly: 'केवल एग्रीगेट',
    modulesVisible: 'मॉड्यूल दिख रहे हैं',
    upToDate: 'अप टू डेट',
    milestones: 'माइलस्टोन और wellbeing notes',
    thisMonth: 'इस महीने',
  },
};

export function t(lang, key) {
  return strings[lang]?.[key] ?? strings.en[key] ?? key;
}

export default strings;
